// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjbmhcoctpwmlqndzybm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYm1oY29jdHB3bWxxbmR6eWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTYwOTUsImV4cCI6MjA1OTA5MjA5NX0.037cUdwLMKpzQc5TTGrsQX3sU1vV6yZ9FdjeWvAA8C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);